### PR TITLE
fix(build): add stub file

### LINKED ISSUE #105: Installation from git master breaks test environment builds
Ref c51063e8ac195db2d2efc69c588db1567bdc18fb

When I install the latest master via `yarn add -D salsify/ember-css-modules`, I can't run tests any more, because of these lines in the dummy app:

https://github.com/salsify/ember-css-modules/blob/c51063e8ac195db2d2efc69c588db1567bdc18fb/tests/dummy/lib/template-stuff/index.js#L14-L23

Running `ember test` or `ember build -e test` causes this error:

```
broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, lstat '/Users/janbuschtoens/clark/application/client/tmp/funnel-input_base_path-UheLAQKH.tmp/vendor/ecm-template-transform.js'
    at Object.lstatSync (fs.js:805:3)
    at symlink (/Users/janbuschtoens/clark/application/node_modules/symlink-or-copy/index.js:99:26)
    at Function.symlinkOrCopySync [as sync] (/Users/janbuschtoens/clark/application/node_modules/symlink-or-copy/index.js:85:5)
    at Funnel._copy (/Users/janbuschtoens/clark/application/node_modules/broccoli-funnel/index.js:494:19)
    at Funnel.processFile (/Users/janbuschtoens/clark/application/node_modules/broccoli-funnel/index.js:477:8)
    at Funnel.applyPatch [as _applyPatch] (/Users/janbuschtoens/clark/application/node_modules/broccoli-funnel/index.js:390:12)
    at Funnel.<anonymous> (/Users/janbuschtoens/clark/application/node_modules/broccoli-funnel/index.js:344:10)
    at Array.forEach (<anonymous>:null:null)
    at Funnel.processFilters (/Users/janbuschtoens/clark/application/node_modules/broccoli-funnel/index.js:343:11)
    at Funnel.build (/Users/janbuschtoens/clark/application/node_modules/broccoli-funnel/index.js:259:10)
    at /Users/janbuschtoens/clark/application/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/Users/janbuschtoens/clark/application/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/janbuschtoens/clark/application/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/janbuschtoens/clark/application/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/janbuschtoens/clark/application/node_modules/rsvp/dist/rsvp.js:2415:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

`ember build -e production` and `ember build -e development` run just fine.

### PR DESCRIPTION
**Pull request by buschtoens**
Fixes #105.

### CODE REVIEW

**Comment by dfreeman** [comment]
This is clearly better than before, as it doesn't break your tests — but it seems like ideally we wouldn't be loading the Ember template compiler when the host is running tests. Rather than adding the stub, maybe it makes sense to have the template-stuff addon no-op if the project name isn't `ember-css-modules`? What do you think?

**Comment by buschtoens** [comment]
Didn't think of that. That's a nifty solution! I'll update the PR.

File: tests/dummy/lib/template-stuff/index.js [hunk 1]
```diff
@@ -11,10 +11,21 @@ module.exports = {
     return true;
   },
 
+  init(parent) {
+    this._super.init && this._super.init.apply(this, arguments);
+
+    let project = parent;
+    while (project.parent) {
+      project = project.parent;
+    }
```
Comment (buschtoens) [inline tests/dummy/lib/template-stuff/index.js]: Since the second parameter to [`init(parent, project)`](https://ember-cli.com/api/classes/Addon.html#method_init) is deprecated I'm using this `while` loop to traverse the tree up to the root, which must be the project.

Is this how the cool kids do it or is there a more elegant solution? 😂

File: tests/dummy/lib/template-stuff/index.js [hunk 2]
```diff
@@ -11,10 +11,21 @@ module.exports = {
...
+
+    this.isDisabled = project.name() !== 'ember-css-modules';
```
Comment (buschtoens) [inline tests/dummy/lib/template-stuff/index.js]: [`project.name()`](https://ember-cli.com/api/classes/Project.html#method_name) is private API, but I don't really see a public API way to access the name of the project. 🤷‍♂️ 

Should I add a comment or is this fine?

File: tests/dummy/lib/template-stuff/index.js (hunk 1 above)
Comment (dfreeman) [reply tests/dummy/lib/template-stuff/index.js]: That I'll definitely work, though `this.project` is also an option 😉

File: tests/dummy/lib/template-stuff/index.js (hunk 2 above)
Comment (dfreeman) [reply tests/dummy/lib/template-stuff/index.js]: I think it's fine. Even though it's marked private, I'd guess usage is [widespread enough](https://emberobserver.com/code-search?codeQuery=project.name) to qualify at least as intimate API at this point

File: tests/dummy/lib/template-stuff/index.js (hunk 1 above)
Comment (buschtoens) [reply tests/dummy/lib/template-stuff/index.js]: I couldn't find any explicit docs on `this project` so I assumed it to be private. Gonna change that then :)

**Comment by buschtoens** [comment]
Seems like all job failures from your linter fix commit are due to some infrastructure problems at Travis. Maybe you can give it a re-run?

**Comment by dfreeman** [comment]
I've noticed that kind of flakiness across a bunch of projects recently 😕 — but the good news is everything's green now. Thanks @buschtoens!
